- name: install glusterfs
  yum: name={{ item }} state=present
  with_items:
    - glusterfs-server

- name: start glusterd
  service: name=glusterd state=started enabled=yes

- name: remove all lvs
  shell: for i in `sudo lvs | grep "g tp_" | awk '{print $2 "/" $5}'` ; do sudo lvremove -f $i ; done
