- name: install glusterfs
  yum: name={{ item }} state=present
  with_items:
    - glusterfs-server

- name: start glusterd
  service: name=glusterd state=started enabled=yes

- name: make /gluster directory
  file: path=/gluster state=directory
